version: '3'
services:

  example_fast:
    build: .
    container_name: example_fast
    ports:
      - 3000:3000
      - 8080:8080
    restart: always
    volumes:
      - ./app:/code
      - ./app/Frontend:/var/www/html